In [25]:
!pip install numpy keras tensorflow scikit-learn scipy tqdm pillow opencv-python optuna
!pip install git+https://github.com/cair/tmu.git

  Using cached opencv_python-4.10.0.84-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (20 kB)
  Using cached optuna-4.0.0-py3-none-any.whl.metadata (16 kB)
  Using cached colorlog-6.8.2-py3-none-any.whl.metadata (10 kB)
Using cached opencv_python-4.10.0.84-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (62.5 MB)
Using cached optuna-4.0.0-py3-none-any.whl (362 kB)
Using cached colorlog-6.8.2-py3-none-any.whl (11 kB)
  Cloning https://github.com/cair/tmu.git to /tmp/pip-req-build-vvpd90z4
  Running command git clone --filter=blob:none --quiet https://github.com/cair/tmu.git /tmp/pip-req-build-vvpd90z4
  Resolved https://github.com/cair/tmu.git to commit df55ecb3c200b85489ac77fbb8d9a3bc9f7e0483
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Using cached xxhash-3.5.0-cp311

In [26]:
!pip install git+https://github.com/cair/GraphTsetlinMachine.git

  Cloning https://github.com/cair/GraphTsetlinMachine.git to /tmp/pip-req-build-dsoyzr8d
  Running command git clone --filter=blob:none --quiet https://github.com/cair/GraphTsetlinMachine.git /tmp/pip-req-build-dsoyzr8d
  Resolved https://github.com/cair/GraphTsetlinMachine.git to commit 3b7e02eb80d30622f6a1036d52dbff2722a60c7e
  Preparing metadata (setup.py) ... done
  Created wheel for GraphTsetlinMachine: filename=GraphTsetlinMachine-0.2.0-py3-none-any.whl size=13278 sha256=70d60945b8d9b483dec091fc411b5db7515941f892a5cd2217de18bda83f10bb
  Stored in directory: /tmp/pip-ephem-wheel-cache-2m5f7jlz/wheels/34/cc/e5/cd009a2fbcaf890e64951f3f7dc9df0cdece99f8c85b781178
Successfully built GraphTsetlinMachine


In [27]:
import pandas as pd
import networkx as nx
import numpy as np
from sklearn.model_selection import train_test_split
import matplotlib

# Load the CSV file generated by C program
df = pd.read_csv('hex_game_results_13.csv')
df.shape

(10000000, 3)

In [12]:
# Limit to 10,000 rows(just for more speed processing)
df = df.iloc[:10000]

# Convert 'Moves' column to lists of integers
df['Moves'] = df['Moves'].apply(lambda x: list(map(int, x.split())))

# Check the processed moves
print("Processed Moves:")
print(df['Moves'].head())

# Assuming board size of 13x13 for the Hex game
BOARD_SIZE = 13

# Function to convert moves into a final board state
def get_final_board_state(moves, board_size):
    board = np.zeros((board_size, board_size), dtype=int)
    for i, move in enumerate(moves):
        player = 1 if i % 2 == 0 else 2
        row, col = move // board_size, move % board_size
        board[row, col] = player
    return board

# Add the final board state to the DataFrame
df['FinalBoard'] = df['Moves'].apply(lambda moves: get_final_board_state(moves, BOARD_SIZE))

# Check the final board states
print("Final Board State for the first game:")
print(df['FinalBoard'].iloc[0])

# Split the data into training and testing sets
# We have a 'Winner' column in the dataset for labels
X_train, X_test, Y_train, Y_test = train_test_split(df['FinalBoard'], df['Winner'], test_size=0.2, random_state=42)

# Check the split data
print(f"Training set size: {len(X_train)}")
print(f"Testing set size: {len(X_test)}")

Processed Moves:
0    [41, 155, 167, 106, 29, 144, 68, 36, 75, 163, ...
1                                            [45, 117]
2    [126, 62, 22, 135, 111, 11, 128, 87, 109, 67, ...
3    [142, 123, 93, 121, 18, 72, 145, 97, 78, 148, ...
4                                         [140, 45, 0]
Name: Moves, dtype: object
Final Board State for the first game:
[[0 0 1 0 0 0 0 2 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 2 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 2 0 0]
 [0 0 1 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0 2 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 2 0 0 0]
 [0 0 2 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 2 0 0 0 0 1 0 0]
 [0 2 0 1 0 0 0 0 0 0 0 0 2]
 [0 0 0 0 0 2 0 2 2 0 0 1 1]]
Training set size: 8000
Testing set size: 2000


In [13]:
df.shape

(10000, 4)

In [14]:
df.head()

Game ID  Winner                                              Moves  \
0        0       0  [41, 155, 167, 106, 29, 144, 68, 36, 75, 163, ...   
1        1       1                                          [45, 117]   
2        2       0  [126, 62, 22, 135, 111, 11, 128, 87, 109, 67, ...   
3        3       0  [142, 123, 93, 121, 18, 72, 145, 97, 78, 148, ...   
4        4       0                                       [140, 45, 0]   

                                          FinalBoard  
0  [[0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0], [0, ...  
1  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, ...  
2  [[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0], [0, ...  
3  [[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0], [0, ...  
4  [[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, ...

In [15]:
X_train.iloc[0]

array([[0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 2, 0, 0, 2, 2, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 2, 0, 1, 2, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0]])

In [16]:
# Convert X_train and X_test from Series to lists of NumPy arrays
X_train_list = X_train.tolist()
X_test_list = X_test.tolist()

In [20]:
#X_train_list

In [21]:
def encode_hex_board(hex_board, board_size):
    symbol_names = []
    for i in range(board_size):
        symbol_names.append("C:%d" % (i))  # Column symbols
        symbol_names.append("R:%d" % (i))  # Row symbols

    # Add player and wall symbols
    symbol_names.append("Player1")
    symbol_names.append("Player2")
    symbol_names.append("TouchingRedWall")
    symbol_names.append("TouchingBlueWall")
    

    # Debug: print the symbols
    print(f"Symbol names: {symbol_names}")
    
    number_of_nodes = board_size * board_size
    
    # Initialize the Graphs class with the updated symbol names
    graphs = Graphs(1, symbol_names=symbol_names, hypervector_size=128, hypervector_bits=2)

    # After initializing the Graphs object, check the symbol registration
    print("Registered symbols in the Graphs object:", graphs.symbol_id)

    # Initialize the graph structure
    graphs.set_number_of_graph_nodes(0, number_of_nodes)
    graphs.prepare_node_configuration()
    # Print the registered graph nodes to ensure they exist
    print(f"Registered graph nodes: {graphs.graph_node_id[0]}")

    #manually adding
    graphs.graph_node_id[0] = {}  # Initialize the dictionary for graph 0
    for node_id in range(number_of_nodes):
        graphs.graph_node_id[0][node_id] = node_id  # Manually register each node
    # Check node registration
    print(f"Registered graph nodes: {graphs.graph_node_id[0]}") 

    # Debug: print the board being processed
    print(f"Processing board:\n{hex_board}")
    
    # Fill in the graph nodes with features
    for row in range(board_size):
        for col in range(board_size):
            node_id = row * board_size + col
            cell_value = hex_board[row, col]
            
            # Debug: print each node value being processed
            print(f"Processing node: row={row}, col={col}, value={cell_value}")

            # Add node features (position and ownership)
            graphs.add_graph_node_feature(0, node_id, "C:%d" % col)  # Column symbol
            graphs.add_graph_node_feature(0, node_id, "R:%d" % row)  # Row symbol
            
            if cell_value == 1:
                graphs.add_graph_node_feature(0, node_id, "Player1")  # Player 1
            elif cell_value == 2:
                graphs.add_graph_node_feature(0, node_id, "Player2")  # Player 2
            
            # Add adjacency to wall features (optional)
            if row == 0 or row == board_size - 1:
                graphs.add_graph_node_feature(0, node_id, "TouchingRedWall")
            if col == 0 or col == board_size - 1:
                graphs.add_graph_node_feature(0, node_id, "TouchingBlueWall")
    
    graphs.prepare_edge_configuration()

    # Add edges between adjacent cells in the Hex grid
    for row in range(board_size):
        for col in range(board_size):
            node_id = row * board_size + col
            adjacent_cells = get_adjacent_cells(row, col, board_size)
            for adj_row, adj_col in adjacent_cells:
                adj_node_id = adj_row * board_size + adj_col
                # Add the edge using add_graph_node_edge
                graphs.add_graph_node_edge(0, node_id, adj_node_id, edge_type=1)
    
    graphs.encode()  # Encode the graph after adding all nodes and edges
    
    return graphs
def get_adjacent_cells(row, col, board_size):
    # Define adjacent cells in a hexagonal grid
    adjacent = []
    if row > 0:
        adjacent.append((row - 1, col))  # Up
        if col < board_size - 1:
            adjacent.append((row - 1, col + 1))  # Up-right
    if row < board_size - 1:
        adjacent.append((row + 1, col))  # Down
        if col > 0:
            adjacent.append((row + 1, col - 1))  # Down-left
    if col > 0:
        adjacent.append((row, col - 1))  # Left
    if col < board_size - 1:
        adjacent.append((row, col + 1))  # Right
    return adjacent

In [22]:
from GraphTsetlinMachine.graphs import Graphs
# Encode the final board states into graphs for training and testing
def encode_all_games(board_states, board_size):
    encoded_graphs = []
    
    for board in board_states:
        # Encode the board into a graph
        encoded_graph = encode_hex_board(board, board_size)
        encoded_graphs.append(encoded_graph)
    
    return encoded_graphs

ModuleNotFoundError: No module named 'GraphTsetlinMachine'

In [ ]:
# Encode training and testing data
encoded_train_graphs = encode_all_games(X_train_list, BOARD_SIZE)
encoded_test_graphs = encode_all_games(X_test_list, BOARD_SIZE)

# Check one of the encoded graphs
print("Encoded graph for the first training game:")
print(encoded_train_graphs[0])

Symbol names: ['C:0', 'R:0', 'C:1', 'R:1', 'C:2', 'R:2', 'C:3', 'R:3', 'C:4', 'R:4', 'C:5', 'R:5', 'C:6', 'R:6', 'C:7', 'R:7', 'C:8', 'R:8', 'C:9', 'R:9', 'C:10', 'R:10', 'C:11', 'R:11', 'C:12', 'R:12', 'Player1', 'Player2', 'TouchingRedWall', 'TouchingBlueWall']
Registered symbols in the Graphs object: {'C:0': 0, 'R:0': 1, 'C:1': 2, 'R:1': 3, 'C:2': 4, 'R:2': 5, 'C:3': 6, 'R:3': 7, 'C:4': 8, 'R:4': 9, 'C:5': 10, 'R:5': 11, 'C:6': 12, 'R:6': 13, 'C:7': 14, 'R:7': 15, 'C:8': 16, 'R:8': 17, 'C:9': 18, 'R:9': 19, 'C:10': 20, 'R:10': 21, 'C:11': 22, 'R:11': 23, 'C:12': 24, 'R:12': 25, 'Player1': 26, 'Player2': 27, 'TouchingRedWall': 28, 'TouchingBlueWall': 29}
Registered graph nodes: {}
Registered graph nodes: {0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9, 10: 10, 11: 11, 12: 12, 13: 13, 14: 14, 15: 15, 16: 16, 17: 17, 18: 18, 19: 19, 20: 20, 21: 21, 22: 22, 23: 23, 24: 24, 25: 25, 26: 26, 27: 27, 28: 28, 29: 29, 30: 30, 31: 31, 32: 32, 33: 33, 34: 34, 35: 35, 36: 36, 37: 37,

In [ ]:
# Check one of the encoded graphs
print("Encoded graph for the first training game:")
print(encoded_train_graphs[0])

In [ ]:
#training step
from GraphTsetlinMachine.tm import MultiClassGraphTsetlinMachine

# Initialize the Graph Tsetlin Machine
tm = MultiClassGraphTsetlinMachine(
    number_of_clauses=5000,  # Adjust based on your problem complexity
    T=10000,                 # Threshold
    s=3.9,                   # Specificity parameter
    depth=1,                 # Depth of decision-making
    message_size=128,        # Size of hypervector used in GTM
    message_bits=2,          # Bits per hypervector
    max_included_literals=32  # Maximum literals in each clause
)

# Training loop
epochs = 100  # Adjust the number of epochs as needed
for epoch in range(epochs):
    # Train the model on the encoded training graphs
    tm.fit(encoded_train_graphs, Y_train, epochs=1, incremental=True)
    
    # Calculate the accuracy on the training and testing data
    train_accuracy = 100 * (tm.predict(encoded_train_graphs) == Y_train).mean()
    test_accuracy = 100 * (tm.predict(encoded_test_graphs) == Y_test).mean()
    
    print(f"Epoch {epoch + 1}: Train accuracy = {train_accuracy:.2f}%, Test accuracy = {test_accuracy:.2f}%")
